# Generated by Django 6.1 on 2026-08-29 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. XSS', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Short reminder of what to test')),
                ('is_default', models.BooleanField(default=False, help_text='Default items are seeded once on first run')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Acme Corp', max_length=255)),
                ('platform', models.CharField(help_text='HackerOne / Bugcrowd / Intigriti / Other', max_length=100)),
                ('program_handle', models.CharField(blank=True, help_text='Program handle, used later for API scope-fetching', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='The user this program belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_or_url', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('web', 'Web'), ('mobile', 'Mobile'), ('api', 'API'), ('other', 'Other')], default='web', max_length=50)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('recon', 'Recon'), ('testing', 'Testing'), ('reported', 'Reported')], default='not_started', max_length=50)),
                ('in_scope', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.target')),
            ],
            options={
                'ordering': ['domain_or_url'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Check for Open Redirect', max_length=255)),
                ('note', models.TextField(blank=True, help_text='Findings, payloads tried, evidence')),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('testing', 'Testing'), ('found', 'Found'), ('no_vuln', 'No vuln')], default='not_started', max_length=50)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.asset')),
            ],
            options={
                'ordering': ['-deadline', 'title'],
            },
        ),
    ]
